### ISSUE TITLE
Where are the instructions

### ISSUE THREAD

**Issue by rajaunleashed** [cmty/adonis-algoliasearch#1]
Where are the instructions? I can see only add provider instruction but can't see the full documentation how to use it? Kindly tell me how to use it in controllers?

**Comment by benjamincanac** [comment]
Hey @rajaunleashed,

I've juste updated the README, so it should be easier for you to get started.

Tell me if you need more informations.

**Comment by rajaunleashed** [comment]
Thank you for update. Now I can use it.
